### ISSUE TITLE
fqdnとbasic認証への対応

### ISSUE THREAD

**Issue by 5ym** [daig0rian/epcltvapp#3]

**Comment by 5ym** [comment]
fqdnを設定値として設定できるようにとbasic認証への対応を検討していただけないでしょうか
外部から使用するのが困難です

**Comment by daig0rian** [comment]
UIを検討するうえで参考に教えてほしいのですが、どういった形でEPGStationを外部公開されているのでしょうか？

https://github.com/l3tnun/EPGStation/issues/230
- EPGStation V1.x.x のBasic認証はそのまま外部公開して使することを意図されていないこと

https://twitter.com/l3tnun/status/1312711924467920898
- Basic認証は EPGStation V2.x.x から廃止されたこと

こうした理由から、EPGStation そのものを(ポートマッピングなどで)そのまま外に公開することは考えづらく、Reverse Proxyなどを設置されていると推測いたしますが、そうなるとEPGStation の API の Base URL がどういう形になるのか想像がつきませんでした。

**Comment by 5ym** [comment]
traefikでSSL対応&basic認証をしているのですがプロキシ時にパスの追加等は行っておらず本来の仕様通りのパスになります
![image](https://user-images.githubusercontent.com/13718335/126870901-d361c678-4542-4d83-bef7-1b96d7a276c0.png)

ちなみにkodiなどでiptvを利用する際は`https://user:password@test.test`のような形で入力してます

**Comment by daig0rian** [comment]
なるほど、URLスキームも https になるのですね。（現在は httpで決め打ちしています）
いまはTV のリモコンで文字入力する都合上なるべく文字を少なくするために、 IPv4 アドレス + ポート番号 だけを入力させる形にしていますが、それとは別にAdvancedな設定項目として ”https://user:password@foo.com/api/” のようにAPI の Base URL そのものが入力できるフォームを作ったほうがよさそう、と理解しました。

**Comment by 5ym** [comment]
補足としてhttpでbasic認証を行うとヘッダー内のbasic認証キーが解読できてしまうため外部にbasic認証で公開する場合はSSL(HSTSがあった方が良い)が必須だと思います

**Comment by daig0rian** [comment]
とりあえず対応してみましたが手元にテスト環境がないのでテストをお願い出来ますでしょうか。
Google Play storeでベータテストに参加するか、リリース 1.19 のapkファイルをサイドロードすることによりテストできます。

**Comment by 5ym** [comment]
早々対応ありがとうございます
https://user:pass@test.test/api/
のような形式で入力はできたのですが，録画リストが表示されません
エラーなどは出ておらず，epgstationのログを確認したところアクセス自体がそもそも来ていないようです

**Comment by daig0rian** [comment]
検証ありがとうございます。なるほどですね。

どういう状態かわからなかったので、私も nginx でSSL + Basic Auth.  するリバプロ構築してみました。
その結果、 https://user:pass@test.test/api/　というように user:pass を追加したところで、 このアプリのREST API処理に使われているライブラリの retrofit2 (okhttp3)では user:pass の部分は無視しているようでした。

この状態でもアプリから リクエスト自体は出ています。EPGStationログに出ていないのは、前段のリバプロで認証失敗して落とされているのが原因かと思います。（ nginxのログには 認証が失敗したことが出てた）

ちょっと検討してみます。

**Comment by daig0rian** [comment]
リリース 1.20 でSSL + Basic Auth.が動作することを確認しました。
先ほどストアに流しましたので、逐次リリースされるかと思います。

以下蛇足です。
本アプリが使うライブラリはどちらもメジャーどころのようですが、 UserInfo を含むURLを渡してもライブラリから発行されるhttp/httpsリクエストには認証ヘッダを乗せてくれませんでした。
これはおそらくRFC3986にあるように、

>  "user:password"形式のUserInfo は推奨されず
> アプリケーションはそのようなデータを無視するか、または拒絶するのを選ぶ事ができる

といった事情があるのかと思われます。

とはいえ、ストリーミング界隈ではたいていのプレーヤーは"user:password"形式のUserInfoを解釈しそれに応じたリクエストを投げてくれるのでそちらがスタンダードなように思います。

今回は設定されたBaseURLを ParseしてUserInfoを得て、それぞれのライブラリに設定する改修を入れています。

retrofit2 (okhttp3)  のBasic認証対応
　>  https://stackoverflow.com/questions/43366164/retrofit-and-okhttp-basic-authentication
GlideのBasic認証対応
　>  https://github.com/bumptech/glide/issues/1579

一方で外部プレーヤは 認証ヘッダをきちんと理解してリクエストを投げてくれる様子で、問題なく再生できました。
（内蔵プレーヤーは放置しています。）
