### ISSUE TITLE
外部プレイヤーに MX Player Pro を利用できない

### ISSUE THREAD

**Issue by orumin** [daig0rian/epcltvapp#5]
MX Player Pro をインストールしていた場合であっても、外部プレイヤーを MX Player にしていた場合無料版 MX Player のインストールを要求される

**Comment by daig0rian** [comment]
現在のところ、外部プレイヤーで選択する MX Playe =  MX Playe Free Edition となっているため、このような動作となっています。

これは、[MX Playerのパッケージ名がProとFreeで異なり](https://mx.j2inter.com/api)、

> com.mxtech.videoplayer.pro - Pro Edition
> com.mxtech.videoplayer.ad - Free Edition

現状では[Free Editionの文字列を指定している](https://github.com/daig0rian/epcltvapp/blob/d6ae1997b240d5485b43c9b937cfef4d824ae718/app/src/main/res/values/strings.xml#L51)ためです。
> `<string name="pref_options_movie_player_val_MX"       translatable="false">com.mxtech.videoplayer.ad</string>`

[knzfujii](https://github.com/knzfujii)さんが[Pro版を選択枝に追加する修正を入れられて](https://github.com/knzfujii/epcltvapp/commit/b21afba6ac94bfe2a83e26ed7d60dce63aeb6632)たり、今回Issueを切ってもらったりしているので、外部プレイヤーの選択肢の`MX Player` を `MX Player Free` とし、新たに `MX Player Pro` を加える修正を行いたいと思います。

簡単な修正で済むので、次のリリースには入れられるかなと思います。

**Comment by orumin** [comment]
仕様のほう承知しました。次 release では対応ということで、ありがとうございます！

**Comment by daig0rian** [comment]
1.27に実装されました。各ストアへリリースされたらClose予定です。ストアリリースは2022年1月17週完了を予定。

**Comment by daig0rian** [comment]
ストアリリースされましたのでクローズします！
https://twitter.com/CxZMoXaYyU8OJzD/status/1483791175274442753
